// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: admin.sql

package db

import (
	"context"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admin (
  name, password
) VALUES (
  $1, $2
)
RETURNING id, name, password
`

type CreateAdminParams struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRowContext(ctx, createAdmin, arg.Name, arg.Password)
	var i Admin
	err := row.Scan(&i.ID, &i.Name, &i.Password)
	return i, err
}
