// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: landlord.sql

package db

import (
	"context"
)

const createLandlord = `-- name: CreateLandlord :one
INSERT INTO landlord (
  first_name, last_name, email, phone, password
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, first_name, last_name, phone, email, password
`

type CreateLandlordParams struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Phone     string `json:"phone"`
	Password  string `json:"password"`
}

func (q *Queries) CreateLandlord(ctx context.Context, arg CreateLandlordParams) (Landlord, error) {
	row := q.db.QueryRowContext(ctx, createLandlord,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.Phone,
		arg.Password,
	)
	var i Landlord
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Phone,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const listLandlords = `-- name: ListLandlords :many
SELECT id, first_name, last_name, phone, email, password FROM landlord
ORDER BY first_name
`

func (q *Queries) ListLandlords(ctx context.Context) ([]Landlord, error) {
	rows, err := q.db.QueryContext(ctx, listLandlords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Landlord{}
	for rows.Next() {
		var i Landlord
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Email,
			&i.Password,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
